// <auto-generated/>
#nullable enable
// CS1591: XML doc comments are not required for auto-generated typed client code.
#pragma warning disable CS1591

using System;
using System.Collections.Generic;
using System.Globalization;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading;
using System.Threading.Tasks;

namespace ShortLink.Api.Client;

public partial class SliceApiClient
{
    private readonly HttpClient _http;

    public SliceApiClient(HttpClient http)
    {
        _http = http ?? throw new ArgumentNullException(nameof(http));
        Health = new HealthClient(_http, PrepareRequest);
        Links = new LinksClient(_http, PrepareRequest);
        Redirect = new RedirectClient(_http, PrepareRequest);
    }

    public SliceApiClient(HttpMessageHandler handler) : this(new HttpClient(handler)) { }

    partial void OnRequestPreparing(HttpRequestMessage request);

    private void PrepareRequest(HttpRequestMessage request) => OnRequestPreparing(request);

    public HealthClient Health { get; }
    public LinksClient Links { get; }
    public RedirectClient Redirect { get; }

    private static string FormatRouteValue<T>(T value)
        => Uri.EscapeDataString(Convert.ToString(value, CultureInfo.InvariantCulture) ?? string.Empty);

    private static async Task __ThrowApiException(HttpResponseMessage response, string operation, CancellationToken cancellationToken)
    {
        SliceProblemDetails? problem = null;
        try
        {
            var __body = await response.Content.ReadAsStringAsync(cancellationToken).ConfigureAwait(false);
            if (__body.Length > 0)
            {
                var __mediaType = response.Content.Headers.ContentType?.MediaType;
                if (__mediaType is "application/problem+json" or "application/json")
                {
                    problem = JsonSerializer.Deserialize(__body, SliceApiClientJsonContext.Default.SliceProblemDetails);
                }
            }
        }
        catch (Exception ex) when (ex is not OperationCanceledException) { }
        var __message = problem?.Title ?? $"{operation} failed: {(int)response.StatusCode} {response.ReasonPhrase}";
        throw new SliceApiException(__message, response.StatusCode, problem);
    }

    public sealed class HealthClient
    {
        private readonly HttpClient _http;
        private readonly Action<HttpRequestMessage> _prepareRequest;

        internal HealthClient(HttpClient http, Action<HttpRequestMessage> prepareRequest)
        {
            _http = http;
            _prepareRequest = prepareRequest;
        }

        public async Task<ShortLink.Api.Features.Health.GetHealth.Response> GetHealthAsync(CancellationToken cancellationToken = default)
        {
            var __url = $"/health";
            using var __message = new HttpRequestMessage(HttpMethod.Get, __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "GetHealth", cancellationToken).ConfigureAwait(false);
            }
            return await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.GetHealthResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Health.GetHealth' returned an empty response body.");
        }
    }

    public sealed class LinksClient
    {
        private readonly HttpClient _http;
        private readonly Action<HttpRequestMessage> _prepareRequest;

        internal LinksClient(HttpClient http, Action<HttpRequestMessage> prepareRequest)
        {
            _http = http;
            _prepareRequest = prepareRequest;
        }

        public async Task<ShortLink.Api.Features.Links.CreateLink.Response> CreateLinkAsync(ShortLink.Api.Features.Links.CreateLink.Request req, CancellationToken cancellationToken = default)
        {
            var __url = $"/api/links";
            using var __message = new HttpRequestMessage(new HttpMethod("POST"), __url);
            __message.Content = JsonContent.Create(req, SliceApiClientJsonContext.Default.CreateLinkRequest);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "CreateLink", cancellationToken).ConfigureAwait(false);
            }
            return await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.CreateLinkResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Links.CreateLink' returned an empty response body.");
        }

        public async Task DeleteLinkAsync(long id, CancellationToken cancellationToken = default)
        {
            var __url = $"/api/links/{SliceApiClient.FormatRouteValue(id)}";
            using var __message = new HttpRequestMessage(new HttpMethod("DELETE"), __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "DeleteLink", cancellationToken).ConfigureAwait(false);
            }
        }

        public async Task<ShortLink.Api.Features.Links.GetLinkStats.Response> GetLinkStatsAsync(long id, CancellationToken cancellationToken = default)
        {
            var __url = $"/api/links/{SliceApiClient.FormatRouteValue(id)}/stats";
            using var __message = new HttpRequestMessage(HttpMethod.Get, __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "GetLinkStats", cancellationToken).ConfigureAwait(false);
            }
            return await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.GetLinkStatsResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Links.GetLinkStats' returned an empty response body.");
        }

        public async Task<ShortLink.Api.Features.Links.ListLinks.Response> ListLinksAsync(int page, int pageSize, CancellationToken cancellationToken = default)
        {
            var __url = $"/api/links";
            var __query = new List<string>();
            __query.Add("page=" + SliceApiClient.FormatRouteValue(page));
            __query.Add("pageSize=" + SliceApiClient.FormatRouteValue(pageSize));
            __url += "?" + string.Join("&", __query);
            using var __message = new HttpRequestMessage(HttpMethod.Get, __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "ListLinks", cancellationToken).ConfigureAwait(false);
            }
            return await __response.Content.ReadFromJsonAsync(SliceApiClientJsonContext.Default.ListLinksResponse, cancellationToken).ConfigureAwait(false)
                ?? throw new HttpRequestException("Route 'Links.ListLinks' returned an empty response body.");
        }
    }

    public sealed class RedirectClient
    {
        private readonly HttpClient _http;
        private readonly Action<HttpRequestMessage> _prepareRequest;

        internal RedirectClient(HttpClient http, Action<HttpRequestMessage> prepareRequest)
        {
            _http = http;
            _prepareRequest = prepareRequest;
        }

        public async Task FollowLinkAsync(string code, CancellationToken cancellationToken = default)
        {
            var __url = $"/r/{SliceApiClient.FormatRouteValue(code)}";
            using var __message = new HttpRequestMessage(new HttpMethod("GET"), __url);
            _prepareRequest(__message);
            using var __response = await _http.SendAsync(__message, cancellationToken).ConfigureAwait(false);
            if (!__response.IsSuccessStatusCode)
            {
                await SliceApiClient.__ThrowApiException(__response, "FollowLink", cancellationToken).ConfigureAwait(false);
            }
        }
    }

    public sealed class SliceProblemDetails
    {
        public string? Type { get; set; }
        public string? Title { get; set; }
        public int? Status { get; set; }
        public string? Detail { get; set; }
        public IReadOnlyDictionary<string, string[]>? Errors { get; set; }
    }

    public class SliceApiException : HttpRequestException
    {
        public SliceProblemDetails? Problem { get; }
        public IReadOnlyDictionary<string, string[]>? Errors => Problem?.Errors;
        public SliceApiException(string message, HttpStatusCode statusCode, SliceProblemDetails? problem)
            : base(message, null, statusCode)
        {
            Problem = problem;
        }
    }
}

[JsonSourceGenerationOptions(PropertyNameCaseInsensitive = true)]
[JsonSerializable(typeof(ShortLink.Api.Features.Links.ListLinks.Response), TypeInfoPropertyName = "ListLinksResponse")]
[JsonSerializable(typeof(ShortLink.Api.Features.Links.CreateLink.Request), TypeInfoPropertyName = "CreateLinkRequest")]
[JsonSerializable(typeof(ShortLink.Api.Features.Links.CreateLink.Response), TypeInfoPropertyName = "CreateLinkResponse")]
[JsonSerializable(typeof(ShortLink.Api.Features.Links.GetLinkStats.Response), TypeInfoPropertyName = "GetLinkStatsResponse")]
[JsonSerializable(typeof(ShortLink.Api.Features.Health.GetHealth.Response), TypeInfoPropertyName = "GetHealthResponse")]
[JsonSerializable(typeof(SliceApiClient.SliceProblemDetails))]
internal sealed partial class SliceApiClientJsonContext : JsonSerializerContext
{
}
